"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Check, Star } from "lucide-react"
import { useState } from "react"

export default function PricingPage() {
  const [isYearly, setIsYearly] = useState(true)

  const features = [
    {
      name: "Template Access",
      free: "Free Templates",
      pro: "All Templates (Free & Pro)",
    },
    {
      name: "AI-Powered Text Generation",
      free: "Basic",
      pro: "Advanced",
    },
    {
      name: "Download Formats",
      free: "Standard Quality (JPG)",
      pro: "High-Resolution (JPG & PNG)",
    },
    {
      name: "Watermark",
      free: "Small 'Generated by Greeting Cards' watermark (removable)",
      pro: "No Watermark",
    },
    {
      name: "Customer Support",
      free: "",
      pro: "Priority Support",
    },
  ]

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      <Navbar />
      <main className="container mx-auto px-4 pt-20 pb-16">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Simple, Flexible Pricing
          </h1>
          <p className="text-xl text-gray-600">
            Choose the plan that's right for you
          </p>
        </div>

        {/* Billing Toggle */}
        <div className="flex justify-center mb-12">
          <div className="inline-flex items-center bg-white rounded-lg border border-gray-200 p-1 shadow-sm">
            <button
              onClick={() => setIsYearly(false)}
              className={`px-6 py-2 rounded-md text-sm font-medium transition-all ${
                !isYearly
                  ? "bg-blue-600 text-white"
                  : "text-gray-600 hover:text-gray-900"
              }`}
            >
              Monthly
            </button>
            <button
              onClick={() => setIsYearly(true)}
              className={`px-6 py-2 rounded-md text-sm font-medium transition-all flex items-center gap-2 ${
                isYearly
                  ? "bg-blue-600 text-white"
                  : "text-gray-600 hover:text-gray-900"
              }`}
            >
              Yearly (Save 50%)
              {isYearly && (
                <div className="w-2 h-2 bg-white rounded-full"></div>
              )}
            </button>
          </div>
        </div>

        {/* Pricing Cards */}
        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto mb-16">
          {/* Free Plan */}
          <Card className="relative bg-white border-2 border-gray-200 shadow-lg overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-blue-50/50 to-white opacity-50"></div>
            <CardHeader className="relative">
              <CardTitle className="text-3xl font-bold text-blue-600 mb-2">
                Free
              </CardTitle>
              <div className="mt-4">
                <span className="text-5xl font-bold text-gray-900">$0</span>
                <span className="text-gray-600 text-lg">/mo</span>
              </div>
            </CardHeader>
            <CardContent className="relative">
              <ul className="space-y-4 mb-6">
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Access to Free Templates</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Basic AI-Powered Text Generation</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Download in Standard Quality (JPG)</span>
                </li>
              </ul>
              <Link href="/auth/signin">
                <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white">
                  Get Started for Free
                </Button>
              </Link>
            </CardContent>
          </Card>

          {/* Pro Plan */}
          <Card className="relative bg-white border-2 border-blue-200 shadow-lg overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-blue-50/50 to-white opacity-50"></div>
            <Badge className="absolute top-4 right-4 bg-yellow-400 text-yellow-900 flex items-center gap-1">
              <Star className="h-3 w-3 fill-yellow-900" />
              Best Value!
            </Badge>
            <CardHeader className="relative">
              <CardTitle className="text-3xl font-bold text-blue-600 mb-2">
                Pro
              </CardTitle>
              <div className="mt-4">
                <span className="text-5xl font-bold text-gray-900">
                  ${isYearly ? "4.50" : "9"}
                </span>
                <span className="text-gray-600 text-lg">/mo</span>
              </div>
              {isYearly && (
                <p className="text-sm text-gray-500 mt-2">
                  Billed yearly at{" "}
                  <span className="line-through">$108</span>{" "}
                  <span className="text-blue-600 font-semibold">$4.50/mo</span>
                </p>
              )}
            </CardHeader>
            <CardContent className="relative">
              <ul className="space-y-4 mb-6">
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Access to All Templates (Free & Pro)</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Premium AI-Powered Text Generation</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">High-Resolution Downloads (JPG & PNG)</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Remove Watermark from Cards</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Priority Customer Support</span>
                </li>
              </ul>
              <Link href="/auth/signin">
                <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white">
                  Get Started
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>

        {/* Comparison Table */}
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-8">
            Compare Features
          </h2>
          <Card className="shadow-lg">
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-gray-200">
                      <th className="text-left py-4 px-6 font-semibold text-gray-900">
                        Feature
                      </th>
                      <th className="text-center py-4 px-6 font-semibold text-gray-900">
                        Free Plan
                      </th>
                      <th className="text-center py-4 px-6 font-semibold text-gray-900">
                        Pro Plan
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {features.map((feature, index) => (
                      <tr
                        key={index}
                        className="border-b border-gray-100 last:border-b-0"
                      >
                        <td className="py-4 px-6 font-medium text-gray-900">
                          {feature.name}
                        </td>
                        <td className="py-4 px-6 text-center">
                          {feature.free ? (
                            <div className="flex flex-col items-center gap-1">
                              <Check className="h-5 w-5 text-blue-600" />
                              <span className="text-sm text-gray-600">
                                {feature.free}
                              </span>
                            </div>
                          ) : (
                            <span className="text-gray-400">—</span>
                          )}
                        </td>
                        <td className="py-4 px-6 text-center">
                          {feature.pro ? (
                            <div className="flex flex-col items-center gap-1">
                              <Check className="h-5 w-5 text-orange-500" />
                              <span className="text-sm text-gray-600">
                                {feature.pro}
                              </span>
                            </div>
                          ) : (
                            <span className="text-gray-400">—</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  )
}
